<?php

namespace AppBundle\Repository;

/**
 * SerialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerialRepository extends \Doctrine\ORM\EntityRepository
{
}
